In [2]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
print(a)

[[1 2 3]
 [2 5 6]
 [6 7 4]]


In [5]:
e = np.eye(3, 4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [6]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
c = np.ones((3, 5))
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
z = np.zeros((3, 5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
v = np.arange(0, 24, 2)
print(v)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [11]:
d = v.reshape((3, 4))
print(d)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [23]:
d[2, 1]

18

In [25]:
d[0, :]

array([0, 2, 4, 6])

In [26]:
d[:, 3]

array([ 6, 14, 22])

In [27]:
d[[0, 1], [0, 2]]

array([ 0, 12])

In [28]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

In [29]:
a
a.shape

(3,)

In [30]:
b
b.shape

(3, 1)

In [34]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
print(f'a = \n{a}')
print(f'b = \n{b}')

a = 
[[1 0]
 [0 1]]
b = 
[[4 1]
 [2 2]]


In [32]:
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [35]:
a.dot(b)

array([[4, 1],
       [2, 2]])

In [37]:
c = np.array([1, 2])
print(c)

[1 2]


In [38]:
np.dot(a, c)

array([1, 2])

In [39]:
a.dot(c)

array([1, 2])

In [41]:
r = a * b
print(r)

[[4 0]
 [0 2]]


In [42]:
a = np.array([[1, 2], [3, 4]])
b = np.transpose(a)
c = a.T

In [43]:
print(a)
print(b)
print(c)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [44]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
det = np.linalg.det(a)

In [45]:
print(a)
print(det)

[[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
-1.0


In [46]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 2]])
r = np.linalg.matrix_rank(a)

In [47]:
print(a)
print(r)

[[1 2 3]
 [1 1 1]
 [2 2 2]]
2


In [48]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])
c = np.array([2, 3, 5])
m = np.array([a, b, c])

In [56]:
np.linalg.matrix_rank(m) == m.shape[0]

True

In [55]:
m.shape

(3, 3)

In [57]:
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(a, b)

In [58]:
print(x)

[2. 3.]


In [59]:
a.dot(x)

array([9., 8.])

In [61]:
a = np.array([[0, 1], [1, 1], [2, 1], [3, 1]])
b = np.array([-1, 0.2, 0.9, 2.1])
x, res, r, s = np.linalg.lstsq(a, b)
print(a)
print(b)
print(x, res, r, s)

[[0 1]
 [1 1]
 [2 1]
 [3 1]]
[-1.   0.2  0.9  2.1]
[ 1.   -0.95] [0.05] 2 [4.10003045 1.09075677]


/home/mike/PycharmProjects/Math_phystech/venv/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


In [62]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
b = np.linalg.inv(a)
print(a)
print(b)

[[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
[[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]


In [63]:
print(np.dot(a, b))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [64]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
print(a)
print(w)
print(v)

[[-1 -6]
 [ 2  6]]
[2. 3.]
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


In [72]:
r = np.array([-0.89442719,  0.83205029])
g = 2.
print(np.dot(g, r))
print(np.dot(a, r))

[-1.78885438  1.66410058]
[-4.09787455  3.20344736]


In [68]:
3.20344736 / 1.66410058


1.9250322958243307

In [75]:
print(np.dot(a, v[0]))
print(np.dot(w[0], v[0]))

[-4.09787458  3.20344738]
[-1.78885438  1.66410059]


In [76]:
np.dot(a, v[0])[0] / np.dot(w[0], v[0])[0]

2.29078152825719

In [86]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [79]:
np.arange(1, 13, 2).reshape((3, 2))

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [83]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
 a = np.eye(4, 5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [85]:
a[[0, 3], [1, 3]]

array([0., 1.])

In [89]:
a = np.eye(4, 5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [90]:
a[[0, 3], [1, 3]]

array([0., 1.])